#ifndef APP_BUILD_CONFIG_H
#define APP_BUILD_CONFIG_H

#include "app_audio_deployment_config.h"

/* Shared firmware build-time controls.
 *
 * Keep default values and cross-module dependency checks here so application
 * sources only consume APP_* controls instead of defining their own local
 * defaults. Module-specific sizing/timing constants remain in their owning
 * headers.
 */

/* Runtime modes */
#ifndef APP_RUNTIME_MODE_AUDIO_PREPROCESS
#define APP_RUNTIME_MODE_AUDIO_PREPROCESS         (0u)
#endif

#ifndef APP_RUNTIME_MODE_CSV_EXPORT
#define APP_RUNTIME_MODE_CSV_EXPORT               (1u)
#endif

#ifndef APP_RUNTIME_MODE_MIC_SELF_TEST
#define APP_RUNTIME_MODE_MIC_SELF_TEST            (2u)
#endif

#ifndef APP_RUNTIME_MODE
#define APP_RUNTIME_MODE                          APP_RUNTIME_MODE_AUDIO_PREPROCESS
#endif

#ifndef APP_AUDIO_REPLAY_TEST_ENABLE
#define APP_AUDIO_REPLAY_TEST_ENABLE              (0u)
#endif

#ifndef APP_AUDIO_REPLAY_ASSET_ID
#define APP_AUDIO_REPLAY_ASSET_ID                 (0xFFFFFFFFu)
#endif

/* Core mode and diagnostic toggles */
#ifndef APP_MODEL_RESULT_MONITOR_ENABLE
#define APP_MODEL_RESULT_MONITOR_ENABLE           (1u)
#endif

#ifndef APP_MODEL_LOG_RESULT_ENABLE
#define APP_MODEL_LOG_RESULT_ENABLE               (0u)
#endif

#ifndef APP_MODEL_LOG_DEMO_COUGH_ONLY_ENABLE
#define APP_MODEL_LOG_DEMO_COUGH_ONLY_ENABLE      (0u)
#endif

#ifndef APP_MODEL_LOG_CONFIRMED_EVENT_ENABLE
#define APP_MODEL_LOG_CONFIRMED_EVENT_ENABLE      (0u)
#endif

#ifndef APP_UART_SANITY_TEST_ENABLE
#define APP_UART_SANITY_TEST_ENABLE               (0u)
#endif

#ifndef APP_BLE_ENABLE
#define APP_BLE_ENABLE                            (0u)
#endif

#ifndef APP_BLE_FAKE_DATA_ENABLE
#define APP_BLE_FAKE_DATA_ENABLE                  (0u)
#endif

#ifndef APP_BLE_STACK_ENABLE
#define APP_BLE_STACK_ENABLE                      (0u)
#endif

#ifndef APP_BLE_SUMMARY_ENABLE
#define APP_BLE_SUMMARY_ENABLE                    (0u)
#endif

#ifndef APP_BLE_LOG_LEVEL
#define APP_BLE_LOG_LEVEL                         (0u)
#endif

#ifndef APP_BLE_DEBUG_DISABLE_INFERENCE
#define APP_BLE_DEBUG_DISABLE_INFERENCE           (0u)
#endif

#ifndef APP_DISPLAY_OFFICIAL_CM55_BRINGUP_ENABLE
#define APP_DISPLAY_OFFICIAL_CM55_BRINGUP_ENABLE  (0u)
#endif

#ifndef APP_CM55_INFERENCE_ENABLE
#define APP_CM55_INFERENCE_ENABLE                 (1u)
#endif

#ifndef APP_DISPLAY_CM33_LAUNCHER_HEARTBEAT_ENABLE
#define APP_DISPLAY_CM33_LAUNCHER_HEARTBEAT_ENABLE (0u)
#endif

#ifndef APP_DISPLAY_CM33_LAUNCHER_UART_ENABLE
#define APP_DISPLAY_CM33_LAUNCHER_UART_ENABLE     (0u)
#endif

#ifndef APP_DISPLAY_DIAG_ENABLE
#define APP_DISPLAY_DIAG_ENABLE                   (0u)
#endif

#ifndef APP_DISPLAY_CM33_DIAG_POLL_ENABLE
#define APP_DISPLAY_CM33_DIAG_POLL_ENABLE         (0u)
#endif

#ifndef APP_DISPLAY_CM55_UART_LOG_ENABLE
#define APP_DISPLAY_CM55_UART_LOG_ENABLE          (0u)
#endif

#ifndef APP_DISPLAY_ENABLE
#define APP_DISPLAY_ENABLE                        (0u)
#endif

#ifndef APP_DISPLAY_SMOKE_ENABLE
#define APP_DISPLAY_SMOKE_ENABLE                  (0u)
#endif

#ifndef APP_DISPLAY_DEBUG_PAGE_ENABLE
#define APP_DISPLAY_DEBUG_PAGE_ENABLE             (0u)
#endif

#ifndef APP_DISPLAY_SUMMARY_ENABLE
#define APP_DISPLAY_SUMMARY_ENABLE                (0u)
#endif

#ifndef APP_DISPLAY_PRODUCT_SCREEN_ENABLE
#define APP_DISPLAY_PRODUCT_SCREEN_ENABLE         (0u)
#endif

#ifndef APP_DISPLAY_FINAL_MOCK_ENABLE
#define APP_DISPLAY_FINAL_MOCK_ENABLE             (0u)
#endif

#ifndef APP_DISPLAY_FINAL_MOCK_PERIOD_MS
#define APP_DISPLAY_FINAL_MOCK_PERIOD_MS          (1000u)
#endif

#ifndef APP_DISPLAY_FINAL_UART_LOG_ENABLE
#define APP_DISPLAY_FINAL_UART_LOG_ENABLE         (1u)
#endif

#ifndef APP_DISPLAY_LOG_COUNT_ENABLE
#define APP_DISPLAY_LOG_COUNT_ENABLE              (0u)
#endif

#ifndef APP_DISPLAY_NULL_SNAPSHOT_LOG_ENABLE
#define APP_DISPLAY_NULL_SNAPSHOT_LOG_ENABLE      (0u)
#endif

#ifndef APP_DISPLAY_NULL_PAGE_LOG_ENABLE
#define APP_DISPLAY_NULL_PAGE_LOG_ENABLE          (0u)
#endif

#ifndef APP_DISPLAY_LCD_ENABLE
#define APP_DISPLAY_LCD_ENABLE                    (0u)
#endif

#ifndef APP_DISPLAY_LCD_SMOKE_ONLY
#define APP_DISPLAY_LCD_SMOKE_ONLY                (0u)
#endif

#ifndef APP_DISPLAY_LCD_SKIP_PANEL_RESET
#define APP_DISPLAY_LCD_SKIP_PANEL_RESET          (0u)
#endif

#ifndef APP_DISPLAY_LCD_SKIP_GFXSS_INIT
#define APP_DISPLAY_LCD_SKIP_GFXSS_INIT           (0u)
#endif

#ifndef APP_DISPLAY_LCD_PANEL_POST_RESET_DELAY_MS
#define APP_DISPLAY_LCD_PANEL_POST_RESET_DELAY_MS (120u)
#endif

#ifndef APP_DISPLAY_LCD_DRIVER_SELECT
#define APP_DISPLAY_LCD_DRIVER_SELECT             (0u)
#endif

#ifndef APP_DISPLAY_LCD_BACKLIGHT_SMOKE_ONLY
#define APP_DISPLAY_LCD_BACKLIGHT_SMOKE_ONLY      (0u)
#endif

#ifndef APP_MONITOR_SUMMARY_ENABLE
#define APP_MONITOR_SUMMARY_ENABLE                (0u)
#endif

#ifndef APP_MONITOR_SUMMARY_DIAG_ENABLE
#define APP_MONITOR_SUMMARY_DIAG_ENABLE           (0u)
#endif

#ifndef APP_MONITOR_SUMMARY_MOCK_ENABLE
#define APP_MONITOR_SUMMARY_MOCK_ENABLE           (0u)
#endif

#ifndef APP_MONITOR_SUMMARY_EVENT_RING_SIZE
#define APP_MONITOR_SUMMARY_EVENT_RING_SIZE       (32u)
#endif

#ifndef APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_ENABLE
#define APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_ENABLE   (0u)
#endif

#ifndef APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_DIAG_ENABLE
#define APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_DIAG_ENABLE (0u)
#endif

#ifndef APP_DISPLAY_LVGL_ENABLE
#define APP_DISPLAY_LVGL_ENABLE                   (0u)
#endif

#ifndef APP_DISPLAY_LVGL_SKIP_SNAPSHOT_READ_ENABLE
#define APP_DISPLAY_LVGL_SKIP_SNAPSHOT_READ_ENABLE (0u)
#endif

#ifndef APP_DISPLAY_LVGL_SNAPSHOT_PROBE_ENABLE
#define APP_DISPLAY_LVGL_SNAPSHOT_PROBE_ENABLE    (0u)
#endif

#ifndef APP_DISPLAY_LVGL_MINIMAL_REALTIME_ENABLE
#define APP_DISPLAY_LVGL_MINIMAL_REALTIME_ENABLE  (0u)
#endif

#ifndef APP_DISPLAY_LVGL_FOOTER_DIAG_ENABLE
#define APP_DISPLAY_LVGL_FOOTER_DIAG_ENABLE       (0u)
#endif

#ifndef APP_DISPLAY_LVGL_TOUCH_ENABLE
#define APP_DISPLAY_LVGL_TOUCH_ENABLE             (0u)
#endif

#ifndef APP_DISPLAY_LVGL_TOUCH_DIAG_ENABLE
#define APP_DISPLAY_LVGL_TOUCH_DIAG_ENABLE        (0u)
#endif

#ifndef APP_RADAR_BRIDGE_ENABLE
#define APP_RADAR_BRIDGE_ENABLE                   (0u)
#endif

#ifndef APP_RADAR_BRIDGE_LOG_ENABLE
#define APP_RADAR_BRIDGE_LOG_ENABLE               (0u)
#endif

#ifndef APP_UART_RADAR_TEST_ENABLE
#define APP_UART_RADAR_TEST_ENABLE                (0u)
#endif

#ifndef APP_BOARD_TIME_NVM_ENABLE
#define APP_BOARD_TIME_NVM_ENABLE                 (1u)
#endif

#ifndef APP_BOARD_TIME_NVM_DIAG_ENABLE
#define APP_BOARD_TIME_NVM_DIAG_ENABLE            (0u)
#endif

#ifndef APP_BOARD_TIME_BOOTSTRAP_EPOCH_S
#define APP_BOARD_TIME_BOOTSTRAP_EPOCH_S          (0u)
#endif

#ifndef APP_BOARD_TIME_BOOTSTRAP_SAVE_NVM_ENABLE
#define APP_BOARD_TIME_BOOTSTRAP_SAVE_NVM_ENABLE  (1u)
#endif

#if ((APP_RUNTIME_MODE != APP_RUNTIME_MODE_AUDIO_PREPROCESS) && \
     (APP_RUNTIME_MODE != APP_RUNTIME_MODE_CSV_EXPORT) && \
     (APP_RUNTIME_MODE != APP_RUNTIME_MODE_MIC_SELF_TEST))
#error "Unsupported APP_RUNTIME_MODE"
#endif

#if ((APP_MODEL_RESULT_MONITOR_ENABLE != 0u) && \
     (APP_MODEL_RESULT_MONITOR_ENABLE != 1u))
#error "Unsupported APP_MODEL_RESULT_MONITOR_ENABLE"
#endif

#if ((APP_AUDIO_REPLAY_TEST_ENABLE != 0u) && \
     (APP_AUDIO_REPLAY_TEST_ENABLE != 1u))
#error "Unsupported APP_AUDIO_REPLAY_TEST_ENABLE"
#endif

#if ((APP_AUDIO_REPLAY_TEST_ENABLE != 0u) && \
     (APP_RUNTIME_MODE != APP_RUNTIME_MODE_AUDIO_PREPROCESS))
#error "APP_AUDIO_REPLAY_TEST_ENABLE requires APP_RUNTIME_MODE_AUDIO_PREPROCESS"
#endif

#if ((APP_AUDIO_REPLAY_TEST_ENABLE != 0u) && \
     (APP_BLE_DEBUG_DISABLE_INFERENCE != 0u))
#error "APP_AUDIO_REPLAY_TEST_ENABLE conflicts with APP_BLE_DEBUG_DISABLE_INFERENCE"
#endif

#if ((APP_MODEL_LOG_RESULT_ENABLE != 0u) && \
     (APP_MODEL_LOG_RESULT_ENABLE != 1u))
#error "Unsupported APP_MODEL_LOG_RESULT_ENABLE"
#endif

#if ((APP_MODEL_LOG_DEMO_COUGH_ONLY_ENABLE != 0u) && \
     (APP_MODEL_LOG_DEMO_COUGH_ONLY_ENABLE != 1u))
#error "Unsupported APP_MODEL_LOG_DEMO_COUGH_ONLY_ENABLE"
#endif

#if ((APP_MODEL_LOG_CONFIRMED_EVENT_ENABLE != 0u) && \
     (APP_MODEL_LOG_CONFIRMED_EVENT_ENABLE != 1u))
#error "Unsupported APP_MODEL_LOG_CONFIRMED_EVENT_ENABLE"
#endif

#if ((APP_UART_SANITY_TEST_ENABLE != 0u) && \
     (APP_UART_SANITY_TEST_ENABLE != 1u))
#error "Unsupported APP_UART_SANITY_TEST_ENABLE"
#endif

#if ((APP_BLE_ENABLE != 0u) && (APP_BLE_ENABLE != 1u))
#error "Unsupported APP_BLE_ENABLE"
#endif

#if ((APP_BLE_FAKE_DATA_ENABLE != 0u) && (APP_BLE_FAKE_DATA_ENABLE != 1u))
#error "Unsupported APP_BLE_FAKE_DATA_ENABLE"
#endif

#if ((APP_BLE_STACK_ENABLE != 0u) && (APP_BLE_STACK_ENABLE != 1u))
#error "Unsupported APP_BLE_STACK_ENABLE"
#endif

#if ((APP_BLE_SUMMARY_ENABLE != 0u) && (APP_BLE_SUMMARY_ENABLE != 1u))
#error "Unsupported APP_BLE_SUMMARY_ENABLE"
#endif

#if (APP_BLE_LOG_LEVEL > 2u)
#error "Unsupported APP_BLE_LOG_LEVEL"
#endif

#if ((APP_BLE_DEBUG_DISABLE_INFERENCE != 0u) && \
     (APP_BLE_DEBUG_DISABLE_INFERENCE != 1u))
#error "Unsupported APP_BLE_DEBUG_DISABLE_INFERENCE"
#endif

#if ((APP_DISPLAY_OFFICIAL_CM55_BRINGUP_ENABLE != 0u) && \
     (APP_DISPLAY_OFFICIAL_CM55_BRINGUP_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_OFFICIAL_CM55_BRINGUP_ENABLE"
#endif

#if ((APP_CM55_INFERENCE_ENABLE != 0u) && (APP_CM55_INFERENCE_ENABLE != 1u))
#error "Unsupported APP_CM55_INFERENCE_ENABLE"
#endif

#if ((APP_DISPLAY_CM33_LAUNCHER_HEARTBEAT_ENABLE != 0u) && \
     (APP_DISPLAY_CM33_LAUNCHER_HEARTBEAT_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_CM33_LAUNCHER_HEARTBEAT_ENABLE"
#endif

#if ((APP_DISPLAY_CM33_LAUNCHER_UART_ENABLE != 0u) && \
     (APP_DISPLAY_CM33_LAUNCHER_UART_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_CM33_LAUNCHER_UART_ENABLE"
#endif

#if ((APP_DISPLAY_DIAG_ENABLE != 0u) && (APP_DISPLAY_DIAG_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_DIAG_ENABLE"
#endif

#if ((APP_DISPLAY_CM33_DIAG_POLL_ENABLE != 0u) && \
     (APP_DISPLAY_CM33_DIAG_POLL_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_CM33_DIAG_POLL_ENABLE"
#endif

#if ((APP_DISPLAY_CM55_UART_LOG_ENABLE != 0u) && \
     (APP_DISPLAY_CM55_UART_LOG_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_CM55_UART_LOG_ENABLE"
#endif

#if ((APP_DISPLAY_ENABLE != 0u) && (APP_DISPLAY_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_ENABLE"
#endif

#if ((APP_DISPLAY_SMOKE_ENABLE != 0u) && (APP_DISPLAY_SMOKE_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_SMOKE_ENABLE"
#endif

#if ((APP_DISPLAY_DEBUG_PAGE_ENABLE != 0u) && \
     (APP_DISPLAY_DEBUG_PAGE_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_DEBUG_PAGE_ENABLE"
#endif

#if ((APP_DISPLAY_SUMMARY_ENABLE != 0u) && \
     (APP_DISPLAY_SUMMARY_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_SUMMARY_ENABLE"
#endif

#if ((APP_DISPLAY_PRODUCT_SCREEN_ENABLE != 0u) && \
     (APP_DISPLAY_PRODUCT_SCREEN_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_PRODUCT_SCREEN_ENABLE"
#endif

#if ((APP_DISPLAY_FINAL_MOCK_ENABLE != 0u) && \
     (APP_DISPLAY_FINAL_MOCK_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_FINAL_MOCK_ENABLE"
#endif

#if ((APP_DISPLAY_FINAL_UART_LOG_ENABLE != 0u) && \
     (APP_DISPLAY_FINAL_UART_LOG_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_FINAL_UART_LOG_ENABLE"
#endif

#if ((APP_DISPLAY_LOG_COUNT_ENABLE != 0u) && \
     (APP_DISPLAY_LOG_COUNT_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LOG_COUNT_ENABLE"
#endif

#if ((APP_DISPLAY_NULL_SNAPSHOT_LOG_ENABLE != 0u) && \
     (APP_DISPLAY_NULL_SNAPSHOT_LOG_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_NULL_SNAPSHOT_LOG_ENABLE"
#endif

#if ((APP_DISPLAY_NULL_PAGE_LOG_ENABLE != 0u) && \
     (APP_DISPLAY_NULL_PAGE_LOG_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_NULL_PAGE_LOG_ENABLE"
#endif

#if ((APP_DISPLAY_LCD_ENABLE != 0u) && (APP_DISPLAY_LCD_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LCD_ENABLE"
#endif

#if ((APP_DISPLAY_LCD_SMOKE_ONLY != 0u) && \
     (APP_DISPLAY_LCD_SMOKE_ONLY != 1u))
#error "Unsupported APP_DISPLAY_LCD_SMOKE_ONLY"
#endif

#if ((APP_DISPLAY_LCD_SKIP_PANEL_RESET != 0u) && \
     (APP_DISPLAY_LCD_SKIP_PANEL_RESET != 1u))
#error "Unsupported APP_DISPLAY_LCD_SKIP_PANEL_RESET"
#endif

#if ((APP_DISPLAY_LCD_SKIP_GFXSS_INIT != 0u) && \
     (APP_DISPLAY_LCD_SKIP_GFXSS_INIT != 1u))
#error "Unsupported APP_DISPLAY_LCD_SKIP_GFXSS_INIT"
#endif

#if ((APP_DISPLAY_LCD_BACKLIGHT_SMOKE_ONLY != 0u) && \
     (APP_DISPLAY_LCD_BACKLIGHT_SMOKE_ONLY != 1u))
#error "Unsupported APP_DISPLAY_LCD_BACKLIGHT_SMOKE_ONLY"
#endif

#if ((APP_MONITOR_SUMMARY_ENABLE != 0u) && \
     (APP_MONITOR_SUMMARY_ENABLE != 1u))
#error "Unsupported APP_MONITOR_SUMMARY_ENABLE"
#endif

#if ((APP_MONITOR_SUMMARY_DIAG_ENABLE != 0u) && \
     (APP_MONITOR_SUMMARY_DIAG_ENABLE != 1u))
#error "Unsupported APP_MONITOR_SUMMARY_DIAG_ENABLE"
#endif

#if ((APP_MONITOR_SUMMARY_MOCK_ENABLE != 0u) && \
     (APP_MONITOR_SUMMARY_MOCK_ENABLE != 1u))
#error "Unsupported APP_MONITOR_SUMMARY_MOCK_ENABLE"
#endif

#if ((APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_ENABLE != 0u) && \
     (APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_ENABLE"
#endif

#if ((APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_DIAG_ENABLE != 0u) && \
     (APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_DIAG_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_CM55_SNAPSHOT_BRIDGE_DIAG_ENABLE"
#endif

#if ((APP_DISPLAY_LVGL_ENABLE != 0u) && (APP_DISPLAY_LVGL_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LVGL_ENABLE"
#endif

#if ((APP_DISPLAY_LVGL_SKIP_SNAPSHOT_READ_ENABLE != 0u) && \
     (APP_DISPLAY_LVGL_SKIP_SNAPSHOT_READ_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LVGL_SKIP_SNAPSHOT_READ_ENABLE"
#endif

#if ((APP_DISPLAY_LVGL_SNAPSHOT_PROBE_ENABLE != 0u) && \
     (APP_DISPLAY_LVGL_SNAPSHOT_PROBE_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LVGL_SNAPSHOT_PROBE_ENABLE"
#endif

#if ((APP_DISPLAY_LVGL_MINIMAL_REALTIME_ENABLE != 0u) && \
     (APP_DISPLAY_LVGL_MINIMAL_REALTIME_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LVGL_MINIMAL_REALTIME_ENABLE"
#endif

#if ((APP_DISPLAY_LVGL_FOOTER_DIAG_ENABLE != 0u) && \
     (APP_DISPLAY_LVGL_FOOTER_DIAG_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LVGL_FOOTER_DIAG_ENABLE"
#endif

#if ((APP_DISPLAY_LVGL_TOUCH_ENABLE != 0u) && \
     (APP_DISPLAY_LVGL_TOUCH_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LVGL_TOUCH_ENABLE"
#endif

#if ((APP_DISPLAY_LVGL_TOUCH_DIAG_ENABLE != 0u) && \
     (APP_DISPLAY_LVGL_TOUCH_DIAG_ENABLE != 1u))
#error "Unsupported APP_DISPLAY_LVGL_TOUCH_DIAG_ENABLE"
#endif

#if ((APP_RADAR_BRIDGE_ENABLE != 0u) && (APP_RADAR_BRIDGE_ENABLE != 1u))
#error "Unsupported APP_RADAR_BRIDGE_ENABLE"
#endif

#if ((APP_RADAR_BRIDGE_LOG_ENABLE != 0u) && \
     (APP_RADAR_BRIDGE_LOG_ENABLE != 1u))
#error "Unsupported APP_RADAR_BRIDGE_LOG_ENABLE"
#endif

#if ((APP_UART_RADAR_TEST_ENABLE != 0u) && \
     (APP_UART_RADAR_TEST_ENABLE != 1u))
#error "Unsupported APP_UART_RADAR_TEST_ENABLE"
#endif

#if ((APP_BOARD_TIME_NVM_ENABLE != 0u) && \
     (APP_BOARD_TIME_NVM_ENABLE != 1u))
#error "Unsupported APP_BOARD_TIME_NVM_ENABLE"
#endif

#if ((APP_BOARD_TIME_NVM_DIAG_ENABLE != 0u) && \
     (APP_BOARD_TIME_NVM_DIAG_ENABLE != 1u))
#error "Unsupported APP_BOARD_TIME_NVM_DIAG_ENABLE"
#endif

#if ((APP_BOARD_TIME_BOOTSTRAP_SAVE_NVM_ENABLE != 0u) && \
     (APP_BOARD_TIME_BOOTSTRAP_SAVE_NVM_ENABLE != 1u))
#error "Unsupported APP_BOARD_TIME_BOOTSTRAP_SAVE_NVM_ENABLE"
#endif

#if ((APP_BLE_STACK_ENABLE != 0u) && (APP_BLE_ENABLE == 0u))
#error "APP_BLE_STACK_ENABLE requires APP_BLE_ENABLE"
#endif

#if ((APP_BLE_SUMMARY_ENABLE != 0u) && \
     ((APP_BLE_ENABLE == 0u) || (APP_MONITOR_SUMMARY_ENABLE == 0u)))
#error "APP_BLE_SUMMARY_ENABLE requires APP_BLE_ENABLE=1 and APP_MONITOR_SUMMARY_ENABLE=1"
#endif

#if ((APP_DISPLAY_SUMMARY_ENABLE != 0u) && (APP_DISPLAY_ENABLE == 0u))
#error "APP_DISPLAY_SUMMARY_ENABLE requires APP_DISPLAY_ENABLE=1"
#endif

#if ((APP_DISPLAY_PRODUCT_SCREEN_ENABLE != 0u) && (APP_DISPLAY_ENABLE == 0u))
#error "APP_DISPLAY_PRODUCT_SCREEN_ENABLE requires APP_DISPLAY_ENABLE=1"
#endif

#if ((APP_DISPLAY_FINAL_MOCK_ENABLE != 0u) && \
     ((APP_DISPLAY_SUMMARY_ENABLE != 0u) || (APP_DISPLAY_SMOKE_ENABLE != 0u)))
#error "APP_DISPLAY_FINAL_MOCK_ENABLE conflicts with APP_DISPLAY_SUMMARY_ENABLE and APP_DISPLAY_SMOKE_ENABLE"
#endif

#if ((APP_DISPLAY_CM33_DIAG_POLL_ENABLE != 0u) && (APP_DISPLAY_DIAG_ENABLE == 0u))
#error "APP_DISPLAY_CM33_DIAG_POLL_ENABLE requires APP_DISPLAY_DIAG_ENABLE=1"
#endif

#if ((APP_DISPLAY_LVGL_ENABLE != 0u) && \
     (APP_DISPLAY_OFFICIAL_CM55_BRINGUP_ENABLE == 0u))
#error "APP_DISPLAY_LVGL_ENABLE requires APP_DISPLAY_OFFICIAL_CM55_BRINGUP_ENABLE=1"
#endif

#if ((APP_RADAR_BRIDGE_ENABLE != 0u) && (APP_UART_RADAR_TEST_ENABLE != 0u))
#error "APP_RADAR_BRIDGE_ENABLE and APP_UART_RADAR_TEST_ENABLE cannot both be 1"
#endif

#if ((APP_BOARD_TIME_BOOTSTRAP_SAVE_NVM_ENABLE != 0u) && \
     (APP_BOARD_TIME_NVM_ENABLE == 0u))
#error "APP_BOARD_TIME_BOOTSTRAP_SAVE_NVM_ENABLE requires APP_BOARD_TIME_NVM_ENABLE=1"
#endif

#endif /* APP_BUILD_CONFIG_H */
