#ifndef APP_AUDIO_DEPLOYMENT_CONFIG_H
#define APP_AUDIO_DEPLOYMENT_CONFIG_H

#define APP_AUDIO_MODEL_SELECT_V2_FLOAT                 (2u)
#define APP_AUDIO_MODEL_SELECT_V3_BOARD_HTK_HARDNEG     (3u)
#define APP_AUDIO_MODEL_SELECT_V3_1_BOARD_FPFIX         (4u)
#define APP_AUDIO_MODEL_SELECT_V3_3_2_B0_CURRENT        (5u)

#ifndef APP_AUDIO_MODEL_SELECT
#define APP_AUDIO_MODEL_SELECT APP_AUDIO_MODEL_SELECT_V2_FLOAT
#endif

#define APP_AUDIO_V3_MODEL_NAME       "audio_model_v3_board_htk_hardneg"
#define APP_AUDIO_V3_MODEL_VERSION    "v3_board_htk_hardneg"
#define APP_AUDIO_V3_FRONTEND_NAME    "board_htk_no_norm_v1"
#define APP_AUDIO_V3_CLASS_ORDER      "non_cough,cough"
#define APP_AUDIO_V3_INPUT_SHAPE      "1x1x40x101"
#define APP_AUDIO_V3_COUGH_THRESHOLD  (0.75f)

#define APP_AUDIO_V3_1_FPFIX_MODEL_NAME       "audio_model_v3_1_fpfix"
#define APP_AUDIO_V3_1_FPFIX_MODEL_VERSION    "v3_1_board_fpfix"
#define APP_AUDIO_V3_1_FPFIX_FRONTEND_NAME    "board_htk_no_norm_v1"
#define APP_AUDIO_V3_1_FPFIX_CLASS_ORDER      "non_cough,cough"
#define APP_AUDIO_V3_1_FPFIX_INPUT_SHAPE      "1x1x40x101"
#define APP_AUDIO_V3_1_FPFIX_COUGH_THRESHOLD  (0.50f)

#define APP_AUDIO_V2_MODEL_NAME       "audio_model_v2_float"
#define APP_AUDIO_V2_MODEL_VERSION    "v2_float"
#define APP_AUDIO_V2_FRONTEND_NAME    "legacy_v2_frontend"
#define APP_AUDIO_V2_CLASS_ORDER      "non_cough,cough"
#define APP_AUDIO_V2_INPUT_SHAPE      "1x1x40x101"
#define APP_AUDIO_V2_COUGH_THRESHOLD  (0.75f)

#define APP_AUDIO_V3_3_2_B0_MODEL_NAME       "audio_model_v3_3_1_planA_A5"
#define APP_AUDIO_V3_3_2_B0_MODEL_VERSION    "v3_3_1_planA_A5"
#define APP_AUDIO_V3_3_2_B0_FRONTEND_NAME    "board_htk_no_norm_v1"
#define APP_AUDIO_V3_3_2_B0_CLASS_ORDER      "non_cough,cough"
#define APP_AUDIO_V3_3_2_B0_INPUT_SHAPE      "1x1x40x101"
#define APP_AUDIO_V3_3_2_B0_COUGH_THRESHOLD  (0.10f)

#if (APP_AUDIO_MODEL_SELECT == APP_AUDIO_MODEL_SELECT_V3_BOARD_HTK_HARDNEG)
#define APP_AUDIO_ACTIVE_MODEL_NAME       APP_AUDIO_V3_MODEL_NAME
#define APP_AUDIO_ACTIVE_MODEL_VERSION    APP_AUDIO_V3_MODEL_VERSION
#define APP_AUDIO_ACTIVE_FRONTEND_NAME    APP_AUDIO_V3_FRONTEND_NAME
#define APP_AUDIO_ACTIVE_CLASS_ORDER      APP_AUDIO_V3_CLASS_ORDER
#define APP_AUDIO_ACTIVE_INPUT_SHAPE      APP_AUDIO_V3_INPUT_SHAPE
#define APP_AUDIO_ACTIVE_COUGH_THRESHOLD  APP_AUDIO_V3_COUGH_THRESHOLD
#define APP_AUDIO_ACTIVE_MODEL_HEADER     "audio_model_v3_board_htk_hardneg_float.h"
#define APP_AUDIO_ACTIVE_TEST_VECTOR_HEADER \
    "audio_test_vectors_v3_board_htk_hardneg.h"
#define APP_AUDIO_ACTIVE_MODEL_API_PREFIX "COUGH"
#define APP_AUDIO_ACTIVE_MODEL_INIT() COUGH_init()
#define APP_AUDIO_ACTIVE_MODEL_COMPUTE(input, output) COUGH_compute((input), (output))
#define APP_AUDIO_ACTIVE_MODEL_SOFT_RESET() COUGH_soft_reset()
#define APP_AUDIO_ACTIVE_MODEL_FINALIZE() COUGH_finalize()
#define APP_AUDIO_ACTIVE_MODEL_RET_SUCCESS COUGH_RET_SUCCESS
#define APP_AUDIO_ACTIVE_MODEL_DATA_OUT_COUNT COUGH_DATA_OUT_COUNT
#elif (APP_AUDIO_MODEL_SELECT == APP_AUDIO_MODEL_SELECT_V3_1_BOARD_FPFIX)
#define APP_AUDIO_ACTIVE_MODEL_NAME       APP_AUDIO_V3_1_FPFIX_MODEL_NAME
#define APP_AUDIO_ACTIVE_MODEL_VERSION    APP_AUDIO_V3_1_FPFIX_MODEL_VERSION
#define APP_AUDIO_ACTIVE_FRONTEND_NAME    APP_AUDIO_V3_1_FPFIX_FRONTEND_NAME
#define APP_AUDIO_ACTIVE_CLASS_ORDER      APP_AUDIO_V3_1_FPFIX_CLASS_ORDER
#define APP_AUDIO_ACTIVE_INPUT_SHAPE      APP_AUDIO_V3_1_FPFIX_INPUT_SHAPE
#define APP_AUDIO_ACTIVE_COUGH_THRESHOLD  APP_AUDIO_V3_1_FPFIX_COUGH_THRESHOLD
#define APP_AUDIO_ACTIVE_MODEL_HEADER     "audio_model_v3.h"
#define APP_AUDIO_ACTIVE_TEST_VECTOR_HEADER \
    "audio_test_vectors_v3_1_fpfix.h"
#define APP_AUDIO_ACTIVE_MODEL_API_PREFIX "AUDIO"
#define APP_AUDIO_ACTIVE_MODEL_INIT() AUDIO_init()
#define APP_AUDIO_ACTIVE_MODEL_COMPUTE(input, output) AUDIO_compute((input), (output))
#define APP_AUDIO_ACTIVE_MODEL_SOFT_RESET() AUDIO_soft_reset()
#define APP_AUDIO_ACTIVE_MODEL_FINALIZE() AUDIO_finalize()
#define APP_AUDIO_ACTIVE_MODEL_RET_SUCCESS AUDIO_RET_SUCCESS
#define APP_AUDIO_ACTIVE_MODEL_DATA_OUT_COUNT AUDIO_DATA_OUT_COUNT
#elif (APP_AUDIO_MODEL_SELECT == APP_AUDIO_MODEL_SELECT_V3_3_2_B0_CURRENT)
#define APP_AUDIO_ACTIVE_MODEL_NAME       APP_AUDIO_V3_3_2_B0_MODEL_NAME
#define APP_AUDIO_ACTIVE_MODEL_VERSION    APP_AUDIO_V3_3_2_B0_MODEL_VERSION
#define APP_AUDIO_ACTIVE_FRONTEND_NAME    APP_AUDIO_V3_3_2_B0_FRONTEND_NAME
#define APP_AUDIO_ACTIVE_CLASS_ORDER      APP_AUDIO_V3_3_2_B0_CLASS_ORDER
#define APP_AUDIO_ACTIVE_INPUT_SHAPE      APP_AUDIO_V3_3_2_B0_INPUT_SHAPE
#define APP_AUDIO_ACTIVE_COUGH_THRESHOLD  APP_AUDIO_V3_3_2_B0_COUGH_THRESHOLD
#define APP_AUDIO_ACTIVE_MODEL_HEADER     "audio_model_v3.3.1_planA_float.h"
#define APP_AUDIO_ACTIVE_TEST_VECTOR_HEADER \
    "audio_test_vectors_v3_3_2_b0.h"
#define APP_AUDIO_ACTIVE_MODEL_API_PREFIX "AUDIO"
#define APP_AUDIO_ACTIVE_MODEL_INIT() AUDIO_init()
#define APP_AUDIO_ACTIVE_MODEL_COMPUTE(input, output) AUDIO_compute((input), (output))
#define APP_AUDIO_ACTIVE_MODEL_SOFT_RESET() AUDIO_soft_reset()
#define APP_AUDIO_ACTIVE_MODEL_FINALIZE() AUDIO_finalize()
#define APP_AUDIO_ACTIVE_MODEL_RET_SUCCESS AUDIO_RET_SUCCESS
#define APP_AUDIO_ACTIVE_MODEL_DATA_OUT_COUNT AUDIO_DATA_OUT_COUNT
#else
#define APP_AUDIO_ACTIVE_MODEL_NAME       APP_AUDIO_V2_MODEL_NAME
#define APP_AUDIO_ACTIVE_MODEL_VERSION    APP_AUDIO_V2_MODEL_VERSION
#define APP_AUDIO_ACTIVE_FRONTEND_NAME    APP_AUDIO_V2_FRONTEND_NAME
#define APP_AUDIO_ACTIVE_CLASS_ORDER      APP_AUDIO_V2_CLASS_ORDER
#define APP_AUDIO_ACTIVE_INPUT_SHAPE      APP_AUDIO_V2_INPUT_SHAPE
#define APP_AUDIO_ACTIVE_COUGH_THRESHOLD  APP_AUDIO_V2_COUGH_THRESHOLD
#define APP_AUDIO_ACTIVE_MODEL_HEADER     "audio_model_v2_float.h"
#define APP_AUDIO_ACTIVE_TEST_VECTOR_HEADER "audio_test_vectors.h"
#define APP_AUDIO_ACTIVE_MODEL_API_PREFIX "AUDIO"
#define APP_AUDIO_ACTIVE_MODEL_INIT() AUDIO_init()
#define APP_AUDIO_ACTIVE_MODEL_COMPUTE(input, output) AUDIO_compute((input), (output))
#define APP_AUDIO_ACTIVE_MODEL_SOFT_RESET() AUDIO_soft_reset()
#define APP_AUDIO_ACTIVE_MODEL_FINALIZE() AUDIO_finalize()
#define APP_AUDIO_ACTIVE_MODEL_RET_SUCCESS AUDIO_RET_SUCCESS
#define APP_AUDIO_ACTIVE_MODEL_DATA_OUT_COUNT AUDIO_DATA_OUT_COUNT
#endif

#endif /* APP_AUDIO_DEPLOYMENT_CONFIG_H */
